chore: update all ci files

diff --git a/.ci/run b/.ci/run
--- a/.ci/run
+++ b/.ci/run
@@ -1,24 +1,36 @@
-#!/bin/bash -eu
+#!/bin/bash
+set -eu
 
 cd "$(dirname "$0")"
-cd ..
+cd .. # git root
 
 if ! command -v sudo; then
-    # CI or Docker sometimes don't have it, so useful to have a dummy
+    # CI or Docker sometimes doesn't have it, so useful to have a dummy
     function sudo {
         "$@"
     }
 fi
 
-if ! [ -z "$CI" ]; then
+# --parallel-live to show outputs while it's running
+tox_cmd='run-parallel --parallel-live'
+if [ -n "${CI-}" ]; then
     # install OS specific stuff here
-    if [[ "$OSTYPE" == "darwin"* ]]; then
+    case "$OSTYPE" in
+    darwin*) 
         # macos
         :
-    else
+        ;;
+    cygwin* | msys* | win*)
+        # windows
+        # ugh. parallel stuff seems super flaky under windows, some random failures, "file used by other process" and crap like that
+        tox_cmd='run'
+        ;;
+    *)
+        # must be linux?
         :
-    fi
+        ;;
+    esac
 fi
 
-pip3 install --user tox
-tox
+# NOTE: expects uv installed
+uv tool run --with tox-uv tox $tox_cmd "$@"
